# Top-level configuration
name = "{{project_name}}-site"
main = "src/_worker.ts"
compatibility_date = "2023-03-14"
send_metrics = false

workers_dev = false
route = { pattern = "{{project_name}}.decentraland.zone/*", zone_name = "{{project_name}}.decentraland.zone" }
tsconfig = "./tsconfig.worker.json"
